# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

# Build settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dirt"
plugins:
  - jekyll-include-cache

# Reading files
include:
  - _pages
exclude:
  - .vs
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Site settings
locale: "en-US"
title: &name Anton Vasin
subtitle: "Principal Software Engineer"
email: mail@vasin.space
description: >- # this means to ignore newlines until "baseurl:"
  Personal page
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vasin.space" # the base hostname & protocol for your site, e.g. http://example.com
repository: "tony-space/tony-space.github.io"
github_username:  tony-space

icons:
  email: &icon-email "fas fa-fw fa-envelope-square"
  github: &icon-github "fab fa-fw fa-github"
  linkedin: &icon-linkedin "fab fa-fw fa-linkedin"
  youtube: &icon-youtube "fab fa-fw fa-youtube"
  medium: &icon-medium "fab fa-fw fa-medium"
  habr: &icon-habr "fas fa-fw fa-link"
  link: "fas fa-fw fa-link"

# Site Author
author:
  name             : *name
  avatar           : "/assets/images/me.jpg"
  bio              : "Master of Science in Software Engineering, a big fan of high-performance GPGPU computing and computer graphics."
  links:
    - label: "mail@vasin.space"
      icon: *icon-email
      url: "mailto:mail@vasin.space"
    - label: "GitHub"
      icon: *icon-github
      url: "https://github.com/tony-space/"
    - label: "LinkedIn"
      icon: *icon-linkedin
      url: "https://linkedin.com/in/tony-space"
    - label: "Youtube"
      icon: *icon-youtube
      url: "https://www.youtube.com/channel/UCmq3iXSJNTzHmaiIxEHURwQ"
    - label: "Medium"
      icon: *icon-medium
      url: "https://tony-space.medium.com/"
    - label: "Habr"
      icon: *icon-habr
      url: "https://habr.com/ru/users/tony-space/posts/"


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true